<div class="row">
    <div class="col-md-12 text-center">
        <h1>Classement Général</h1>
        
        <a class="filter" href="<?= $this->url('classement/men') ?>">
            <button type="button" class="btn btn-primary">Classement Hommes</button>
        </a>
        <a class="filter" href="<?= $this->url('classement/women') ?>">
            <button type="button" class="btn btn-primary">Classement Femmes</button>
    <div class="table-responsive mt-20">
        <table class="table">
            <thead>
                <tr>
                    <td>Dossard</td>
                    <td>Nom</td>
                    <td>Prénom</td>
                    <td>Temps</td>
                </tr>
            </thead>
            <tbody>

                    <?php
                    foreach($all as $participant){ ?>
                        <tr>
                            <td><?=$participant->getBibNumber()?></td>
                            <td><?=$participant->getFirstname()?></td>
                            <td><?=$participant->getLastname()?></td>
                            <td><?= substr($participant->getTime(), 0, 2).'h'.substr($participant->getTime(), 2, 2).'m'.substr($participant->getTime(), 4, 2).'s'.substr($participant->getTime(), 6, 2)?></td>
                        </tr>
                    <?php } ?>                 
            </tbody>
        </table>
    </div>
    </div>
</div>
